### ISSUE TITLE
0.18.6遗漏汉化处

### ISSUE THREAD

**Issue by panpeach** [ender-zhao/Clash-for-Windows_Chinese#13]
配置右边鼠标悬浮刷新处，弹出 update ，此处未汉化
![1](https://user-images.githubusercontent.com/13916352/139519504-c43382ac-ead4-4720-b8b8-d5c1d56e1191.jpg)

**Comment by ender-zhao** [comment]
稍后处理，预计今晚重新发布

**Comment by ender-zhao** [comment]
已发布，请重新下载
