### ISSUE TITLE
windows10 使用UTF-8字符集安装器出现乱码

### ISSUE THREAD

**Issue by Lparksi** [ender-zhao/Clash-for-Windows_Chinese#17]
![image](https://user-images.githubusercontent.com/60086490/147846590-c43a5c54-bd70-4a95-a1a3-ec50aca1c80e.png)
![image](https://user-images.githubusercontent.com/60086490/147846593-3b307823-e924-4da5-bb97-9c92227cc996.png)
![image](https://user-images.githubusercontent.com/60086490/147846605-59facd7c-ab62-452b-9d1a-da858eb08d1c.png)

**Comment by ender-zhao** [comment]
解决方法: 取消勾选`Beta 版`
选定快捷方式中的问号问题将在下个版本解决 (第一个指的是在桌面上创建快捷方式)
