### ISSUE TITLE
Experimental Features翻译

### ISSUE THREAD

**Issue by yhl452493373** [ender-zhao/Clash-for-Windows_Chinese#18]
Experimental Features这个没汉化，翻译火来应该是 实验功能
<img width="850" alt="Experimental Features" src="https://user-images.githubusercontent.com/26134687/148011123-ba882891-9707-419e-9939-a2fb4b8064ad.png">

**Comment by ender-zhao** [comment]
马上处理

**Comment by ender-zhao** [comment]
已发布，请[重新下载](https://github.com/ender-zhao/Clash-for-Windows_Chinese/releases/download/CFW-V0.19.4_CN/app.asar)

**Comment by yhl452493373** [comment]
感谢
