### ISSUE TITLE
。。。

### ISSUE THREAD

**Issue by kljgq** [ender-zhao/Clash-for-Windows_Chinese#19]
为什么导入了代理没法用

**Comment by ender-zhao** [comment]
在原版中，这个问题是否存在？

**Comment by kljgq** [comment]
一开始好像不是这里下的，后来那个也出了带你问题然后就到这下，出现了这个问题但是还能用，现在下这个就用不了了





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月12日(星期三) 中午1:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ender-zhao/Clash-for-Windows_Chinese] 。。。 (Issue #19)





 
在原版中，这个问题是否存在？

**Comment by ender-zhao** [comment]
具体是节点超时还是Clash for Windows不代理流量？

**Comment by kljgq** [comment]
现在好像又可以了，不过全是超时，之前一直都是弹窗说无法导入配置






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月12日(星期三) 下午2:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ender-zhao/Clash-for-Windows_Chinese] 。。。 (Issue #19)





 
具体是节点超时还是Clash for Windows不代理流量？

**Comment by ender-zhao** [comment]
超时和线上导入不了配置应该找机场。
一般超时是节点问题，如果无法从线上导入就说明那个链接被墙了，除非是在配置文件都正确的情况下离线任然无法导入，否则都与Clash的原版和汉化版无关。

**Comment by kljgq** [comment]
因为一样的机场手机上可以用，我就问一下，谢谢哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月12日(星期三) 下午2:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ender-zhao/Clash-for-Windows_Chinese] 。。。 (Issue #19)





 
超时和线上导入不了配置应该找机场。
 一般超时是节点问题，如果无法从线上导入就说明那个链接被墙了，除非是在配置文件都正确的情况下离线任然无法导入，否则都与Clash的原版和汉化版无关。
