### ISSUE TITLE
在切换到有“provider”“提供商”的配置文件时，左边会持续增加“提供商”标签

### ISSUE THREAD

**Issue by zenon3dh** [ender-zhao/Clash-for-Windows_Chinese#2]
英文原版下不会有这个问题，替换app.asar汉化文件后才会出现

如果不停点击带有提供商的配置文件，左边会一直新增“提供商”标签，然后闪退。

**Comment by ender-zhao** [comment]
左边会一直新增“提供商”标签的问题已经确定，但是我在测试中并未遇上闪退。据任务管理器提供的信息，在快速点击提供商时会使CPU利用率增加至90%，这可能与硬件有关

**Comment by ender-zhao** [comment]
目前正在解决

**Comment by ender-zhao** [comment]
解决了，请重新下载一次
