### ISSUE TITLE
无法找到压缩包中的app.asar文件

### ISSUE THREAD

**Issue by hrcarryu** [ender-zhao/Clash-for-Windows_Chinese#20]
可能是我太菜了，我根本找不到所谓的app.asar文件，只有renderer.js和main.js两个文件，鉴于都没有同样的问题，我是不是有哪个地方没有搞懂。

**Comment by ender-zhao** [comment]
?
能详细说明吗？

**Comment by ender-zhao** [comment]
你是需要下载app.asar吗？

**Comment by hrcarryu** [comment]
谢谢回复，我找到文件在哪了，确实是眼神不好
