### ISSUE TITLE
关于clash  for Windows 更新和去广告

### ISSUE THREAD

**Issue by MrE819** [ender-zhao/Clash-for-Windows_Chinese#21]
已按照教程安装好所需软件，下图所示是用什么软件打开的
![附件一](https://user-images.githubusercontent.com/89900111/154204881-f7f6b46a-b420-4d8a-b8f5-67f49abb852b.jpg)

**Comment by MrE819** [comment]
@ender-zhao

**Comment by ender-zhao** [comment]
[Notepad++](https://notepad-plus-plus.org/)

**Comment by ender-zhao** [comment]
推荐的格式化js代码网站: https://www.strerr.com/js-format.html

**Comment by MrE819** [comment]
> [Notepad++](https://notepad-plus-plus.org/)

使用这个软件编辑package.json文件？

**Comment by ender-zhao** [comment]
修改`renderer.js`文件

**Comment by MrE819** [comment]
> 
大佬在更新一下教程的文档呗 Thanks ♪(･ω･)ﾉ

**Comment by ender-zhao** [comment]
asar安装教程中是有关于打包的说明的

**Comment by MrE819** [comment]
> asar安装教程中是有关于打包的说明的

打开之后搜索没有找到 [e._v("广告")]

**Comment by ender-zhao** [comment]
你正在编译的是汉化过的app.asar还是没汉化过的app.asar?

**Comment by MrE819** [comment]
> 你正在编译的是汉化过的app.asar还是没汉化过的app.asar?

正在编译app.asar

**Comment by MrE819** [comment]
重新打包后将app.asar文件复制到\resources目录打开软件一片空白

**Comment by ender-zhao** [comment]
那就是改错东西了

**Comment by MrE819** [comment]
没有啊 按照你的教程来，去除广告

**Comment by ender-zhao** [comment]
你就这么想移除广告吗？

**Comment by MrE819** [comment]
作为开封这当然不希望 用户用着越干净简单越好 看着舒服

**Comment by ender-zhao** [comment]
好吧，给你个已经改好的文件: [下载](
https://public.sn.files.1drv.com/y4mr2KBNvvIKnrTBisql0h9DImbrPanK71Lo_iFi3YnyJ-2Ywu0Ztk_6YDIgM3ssNuN7V3E44heX-V8qgOcqOBqyfaQhRy7m7auFRMlOlyCLOpNE7-Rrse7HLljOEp38EQa5s6S9vixi5R9FKev9EVU-4ou53-lveNI68RxMayi0cFcj9wuh_qEdEwjcdnHKd9WZqxNMasgfbQOI5SXUyqR4l_sOs2rVtKOaWncqHLdwIw)
你可以参考一下哪里你没改对

**Comment by MrE819** [comment]
> 好吧，给你个已经改好的文件: [下载](https://public.sn.files.1drv.com/y4mr2KBNvvIKnrTBisql0h9DImbrPanK71Lo_iFi3YnyJ-2Ywu0Ztk_6YDIgM3ssNuN7V3E44heX-V8qgOcqOBqyfaQhRy7m7auFRMlOlyCLOpNE7-Rrse7HLljOEp38EQa5s6S9vixi5R9FKev9EVU-4ou53-lveNI68RxMayi0cFcj9wuh_qEdEwjcdnHKd9WZqxNMasgfbQOI5SXUyqR4l_sOs2rVtKOaWncqHLdwIw) 你可以参考一下哪里你没改对

怎么赶脚我的文件打开后和你的区别很大，位置错了吗；\dist\electron\rederer.js

**Comment by ender-zhao** [comment]
位置没错

**Comment by ender-zhao** [comment]
你看到的代码是不是只有7行？
