### ISSUE TITLE
汉化更新

### ISSUE THREAD

**Issue by pubproprietary** [ender-zhao/Clash-for-Windows_Chinese#23]
clash更新到0.19.10了

**Comment by pubproprietary** [comment]
0.19.9可以放一放了（笑）

**Comment by ender-zhao** [comment]
我刚汉化好0.19.9
现在你可以去[下载](https://github.com/ender-zhao/Clash-for-Windows_Chinese/releases/tag/CFW-V0.19.9_CN)了

**Comment by ender-zhao** [comment]
然后我马上去汉化0.19.10
大概15分钟后发布

**Comment by pubproprietary** [comment]
辛苦辛苦（花）

**Comment by ender-zhao** [comment]
已更新，但更建议使用0.19.9

**Comment by wohaocaiji** [comment]
> 已更新，但更建议使用0.19.9

为什么更建议0.19.9啊，这个版本不是XSS漏洞没有完全修复嘛

**Comment by ender-zhao** [comment]
主要是0.19.10的 服务模式 , 虚拟网卡安装 和 日志级别中会有几个<br/>和&nbsp;符号，这样看着不美观
