### ISSUE TITLE
您好  请问出现这个错误怎么解决呢

### ISSUE THREAD

**Issue by tangozz1** [ender-zhao/Clash-for-Windows_Chinese#26]
[No connection could be made because the target machine actively refused it](https://www.cnblogs.com/chucklu/p/7879491.html)

**Comment by ender-zhao** [comment]
这个问题与汉化无关，如果与Clash for Windows有关，你或许应该去[这里](https://github.com/Fndroid/clash_for_windows_pkg)提问
