### ISSUE TITLE
配置错误 

### ISSUE THREAD

**Issue by wobupeichifan** [ender-zhao/Clash-for-Windows_Chinese#27]
请问下载后不能连接怎么回事呢 ？之前一直都可以用 ，现在一直显示配置错误 。求回复 ，感谢

**Comment by ender-zhao** [comment]
这个问题是否会在原版中出现？

**Comment by ender-zhao** [comment]
另外，你下载的是配置文件吗？

**Comment by wobupeichifan** [comment]
你好，原版也出现过，用了一段时间后配置出现错误，然后重新下载好多次还是用不了。汉化版和原版都是一样对吗？我都下载过，还是使用不了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月9日(星期三) 下午3:45
收件人: "ender-zhao/Clash-for-Windows_Chinese";
抄送: "Author";
主题: Re: [ender-zhao/Clash-for-Windows_Chinese] 配置错误  (Issue #27)





 
另外，你下载的是配置文件吗？
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wobupeichifan** [comment]
导入配置后显示错误 ，一大串英文，配置也无法更新。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月9日(星期三) 下午5:32
收件人: ***@***.***&gt;; 
抄送: " ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ender-zhao/Clash-for-Windows_Chinese] 配置错误  (Issue #27)





 
是导入配置后无法切换到配置吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ender-zhao** [comment]
那英文写的报错信息是什么？

**Comment by wobupeichifan** [comment]
我刚刚卸载掉了，现在电脑不在，明天截图给你看一下，谢谢你回复这么多，太感谢你啦 ！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ender-zhao/Clash-for-Windows_Chinese"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月9日(星期三) 下午5:40
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [ender-zhao/Clash-for-Windows_Chinese] 配置错误  (Issue #27)





 
那英文写的报错信息是什么？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wobupeichifan** [comment]
你好，麻烦看一下这是什么问题呢 ？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ender-zhao/Clash-for-Windows_Chinese"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月9日(星期三) 下午5:40
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [ender-zhao/Clash-for-Windows_Chinese] 配置错误  (Issue #27)





 
那英文写的报错信息是什么？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ender-zhao** [comment]
你似乎没有提供相关的图片或文本

**Comment by wobupeichifan** [comment]
请问附件可以看到吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ender-zhao/Clash-for-Windows_Chinese"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月10日(星期四) 中午11:17
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [ender-zhao/Clash-for-Windows_Chinese] 配置错误  (Issue #27)





 
你似乎没有提供相关的图片或文本
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ender-zhao** [comment]
看不到，但你可以将图片托拽到`Write`框中进行发送

![image](https://user-images.githubusercontent.com/77391690/157584098-4f84d54f-0bff-4557-88e4-684f52d34d31.png)

**Comment by wobupeichifan** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ender-zhao/Clash-for-Windows_Chinese"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月10日(星期四) 中午11:44
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [ender-zhao/Clash-for-Windows_Chinese] 配置错误  (Issue #27)





 
看不到，但你可以将图片托拽到Write框中进行发送
 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ender-zhao** [comment]
由于看不到报错信息，因此给个大致的解决方法：

如果在下载配置中报错是由网络问题导致的，要么是下载链接被墙，要么就是网不稳定或链接失效，如果是购买的配置，那么建议联系机场造成的，如果不是，你或许应该去[这里](https://github.com/Fndroid/clash_for_windows_pkg)提问

如果是切换到配置时报错，一般是由格式不对造成的，可以通过重写配置解决 (如果不会写，可以去Google下)，或者与你所使用的机场联系，如果格式没问题但问题仍在，那么你应该去[这里](https://github.com/Fndroid/clash_for_windows_pkg)提问
