### ISSUE TITLE
0.19.9后的版本字符不显示

### ISSUE THREAD

**Issue by kidsoyo** [ender-zhao/Clash-for-Windows_Chinese#29]
![image](https://user-images.githubusercontent.com/35915585/158120941-2a5dc664-471d-4828-99f7-b4e8659a5562.png)

**Comment by kidsoyo** [comment]
已解决，自定义字体后就这样，恢复成默认就OK了

**Comment by ender-zhao** [comment]
需要输入正确的字体才能正常显示，比如`华文琥珀`，`Times New Roman`，`华文中宋`或`Algerian`

**Comment by ender-zhao** [comment]
经测试，原版Clash for Windows也存在该问题，你或许应该去[clash_for_windows_pkg](https://github.com/Fndroid/clash_for_windows_pkg)反馈
