### ISSUE TITLE
能不能去广告

### ISSUE THREAD

**Issue by DaveReinger** [ender-zhao/Clash-for-Windows_Chinese#3]
# 关于页面的广告能不能去掉

**Comment by ender-zhao** [comment]
那个页面的广告？

**Comment by ender-zhao** [comment]
Clash For Windows "关于" 中的两个广告是有办法去的，但是这么做会让原作者失去收益，这样不好。其次该项目属于汉化项目，不包括去除广告

**Comment by ender-zhao** [comment]
如果你指的是网站上的广告，请前往https://github.com/Loyalsoldier/clash-rules下载相应屏蔽规则

**Comment by DaveReinger** [comment]
# 好的谢谢

**Comment by ender-zhao** [comment]
尝试性添加了个去除广告的[Clash](https://github.com/ender-zhao/Clash-for-Windows_Chinese/releases/tag/Clash-custom-made)

**Comment by ender-zhao** [comment]
你需要的话可以试试

**Comment by DaveReinger** [comment]
Nice 啊，不过我早已经自己动手改过了

**Comment by DaveReinger** [comment]
# 谢啦！！

**Comment by szkzn** [comment]
我感觉处理的挺好了，放出了2个版本，尽量规避风险了。
我不会点进去看无所谓，就是不知道会不会有其他风险，去广告版不知道会不会引起喷子出没，正如开发者所说“但是这么做会让原作者失去收益，这样不好。其次该项目属于汉化项目”,希望去广告版不会引起什么幺蛾子。如果不行，就下架去广告版也没问题的。

**Comment by ender-zhao** [comment]
> 我觉得处理的新奇了，放瑜伽2个版本，尽量规避避了。
> 我不会点看不知道，就是不知道会不会有其他的，去冒险广告版不会不会被流行喷子知道出没，开发者说“但因为是作者自己的知识，所以不好。其次项目属于汉化项目”，希望去广告版不会引起什么幺蛾子。如果不行，就下架去广告版也不会问题的。

经过我考虑，我确实认为这样做不太好，也违背最开始做的想法；但暂且不会考虑下架，但之后将永不会再去兼容更高版本的clash

**Comment by ender-zhao** [comment]
> 我觉得处理的新奇了，放瑜伽2个版本，尽量规避避了。
> 我不会点看不知道，就是不知道会不会有其他的，去冒险广告版不会不会被流行喷子知道出没，开发者说“但因为是作者自己的知识，所以不好。其次项目属于汉化项目”，希望去广告版不会引起什么幺蛾子。如果不行，就下架去广告版也不会问题的。

之所以这么做是因为有两个人向我提问了，这表明有需求，那么我也就应该回应一下，但多想想也确实认为这样不妥

**Comment by szkzn** [comment]
谨慎点好，主要是有个误会点，你汉化了还去了他广告，还放赞赏码了，有这个心思的人肯定会引起误会，要是没放收款码，想怎么弄就怎么弄，可以随意些，反正也没收钱，纯公益，当然现在也是纯公益（毕竟是自愿赞赏），为了长远发展考虑，稳妥点

**Comment by ender-zhao** [comment]
> 谨慎点好，主要是有个误会点，你汉化了还去了他广告，还放赞赏码了，有这个心思的人肯定会引起误会，要是没放收款码，想怎么弄就怎么弄，可以随意些，反正也没收钱，纯公益，当然现在也是纯公益（毕竟是自愿赞赏），为了长远发展考虑，稳妥点

感谢提醒，那个版本将不再维护

**Comment by coderzhw** [comment]
> Nice 啊，不过我早已经自己动手改过了

请问你是怎么改的啊？
