### ISSUE TITLE
可以提供linux的汉化吗？

### ISSUE THREAD

**Issue by dygtz** [ender-zhao/Clash-for-Windows_Chinese#30]

**Comment by ender-zhao** [comment]
由于我没有Linux系统，我无法测试，但app.asar文件似乎是通用的，你可以试试，如果有我没汉化到的地方就请告诉我

**Comment by ashin520** [comment]
linux建议用shell clash，精简小巧。
windows是没办法，没有脚本clash安装教程，不然我也不想选择带GUI图形界面的版本。

**Comment by yzlqmj** [comment]
Linux可以使用app.asar文件汉化，在Ubuntu和arch下测试没问题。

**Comment by dygtz** [comment]
谢谢，我已经成功汉化了，和Windows一样，都有此文件，替换即可

取得 Android 版 Outlook<https://aka.ms/AAb9ysg>
________________________________
