### ISSUE TITLE
Clash for Windows V0.19.14汉化版 有DD-WRT路由器版本吗？

### ISSUE THREAD

**Issue by HaiwangTT** [ender-zhao/Clash-for-Windows_Chinese#31]
Clash for Windows V0.19.14汉化版 有DD-WRT路由器版本吗？请问怎么下载安装？

**Comment by ender-zhao** [comment]
这个库提供的主要内容是汉化后的`app.asar`如果DD-WRT版本的根目录包含这个文件，那么可能通用。
另外，这里不提供教程，请自行搜索
