### ISSUE TITLE
一点翻译的错误

### ISSUE THREAD

**Issue by Duck-Deng** [ender-zhao/Clash-for-Windows_Chinese#34]
![image](https://user-images.githubusercontent.com/64295725/166130430-05384227-d28d-4507-bbb9-7cb06ebf514c.png)
这个汉化补丁将mixin翻译成了“混淆”，这个功能实际上是向配置文件插入一段公共配置，翻译为“混合配置”或者直接使用英文名更合适

**Comment by Zxilly** [comment]
https://github.com/ender-zhao/Clash-for-Windows_Chinese/blob/aa5cb34274b5880cd70065e2e67e0ac4e58ee600/chinese_file/Auto/renderer-chinese.txt#L110
你可以交个PR
