### ISSUE TITLE
可以把 clash for windows 汉化 打包成 独立单文件版 .exe 吗？

### ISSUE THREAD

**Issue by 1457384613gh** [ender-zhao/Clash-for-Windows_Chinese#35]
考虑到，很多地方很难访问 github 下载 clash，我打算把 clash for windows 汉化版 复制到 U盘里，随身携带。感觉，单文件独立版的.exe 程序比较满足需求。压缩包、文件夹和安装包都有弊端。

- 压缩包需要解压以后才能使用，并不是每台电脑都装了 7-zip，借用别人的电脑，多安装一个软件就有点不礼貌。
- 文件夹复制到电脑里了以后还得寻找主程序创建快捷方式；不创建快捷方式的话，每次都要寻找主程序；倘若文件夹更换了位置，快捷方式就失效了，还得重新弄。倘若从U盘里打开，快捷方式还不一定有用，因为涉及到U盘盘符；每次都得进入U盘，在文件夹中寻找主程序。
- 安装包还得修改注册表，而且有的系统能够运行压缩包解压的主程序，但使用安装包会安装失败。倘若借用别人的电脑，安装以后，还得卸载，不然不礼貌。

- 单文件独立版的.exe，不用解压；不用进入文件夹寻找主程序；不用修改注册表；不涉及安装失败不失败；复制到哪里，都能够直接双击打开；倘若借用别人的电脑，用完以后，只需删除一个文件，操作方便。

所以，我想问下，可以把 clash for windows 汉化 打包成 独立单文件版 .exe 吗？

**Comment by ender-zhao** [comment]
很遗憾，这个做不到，但你可以将clash for windows解压至U盘，然后新建一个`data`(无大小写要求)文件夹，这样就可以防止配置文件被保存至别人的电脑并在移动U盘至其它电脑时，不需要重新下载配置

具体可以参考官方的文档https://docs.cfw.lbyczf.com/contents/7z.html
