### ISSUE TITLE
催更

### ISSUE THREAD

**Issue by Muluo126** [ender-zhao/Clash-for-Windows_Chinese#36]
麻烦大佬更新一下0.19.18，拜托了

**Comment by ender-zhao** [comment]
有点忙，大概晚上更

**Comment by ender-zhao** [comment]
[搞定!](https://github.com/ender-zhao/Clash-for-Windows_Chinese/releases/tag/CFW-V0.19.18_CN)

**Comment by Muluo126** [comment]
非常感谢大佬
