### ISSUE TITLE
mac版能汉化否

### ISSUE THREAD

**Issue by exile799** [ender-zhao/Clash-for-Windows_Chinese#37]
mac版能用这个汉化文件汉化吗？谢谢

**Comment by ender-zhao** [comment]
由于我没有mac系统的电脑因此无法测试，但你可以试试，应该是能用的

**Comment by Luastonsu** [comment]
Mac也可以，找到App显示包内容，替换app.asar重新打开即可

exile799 ***@***.***> 于2022年5月21日周六 19:27写道：

**Comment by exile799** [comment]
这两天比较忙还没试过 这就去安装 非常感谢 谢谢

发自我的iPhone 13 Pro Max

在 2022年5月23日，21:19，WanQiu ***@***.***> 写道：

﻿

Mac也可以，找到App显示包内容，替换app.asar重新打开即可

exile799 ***@***.***> 于2022年5月21日周六 19:27写道：

**Comment by hellowwwwp** [comment]
亲测, mac 版本也支持汉化

**Comment by keeping-sober** [comment]
为啥我下载了文件之后没有压缩包显示的是一个浏览器的符号，然后直接点击下载的东西出来的是一个网址一样的东西，跳转下载一个相同的文件，就很奇怪

**Comment by keeping-sober** [comment]
![image](https://user-images.githubusercontent.com/125372293/218751978-df5a1bf4-4bfa-4ee9-bfb8-814229ac5fe1.png)

**Comment by keeping-sober** [comment]
也没办法解压

**Comment by DuYuren** [comment]
> 

下个压缩软件去吧,比如7-zip

**Comment by zhangdp** [comment]
mac建议使用clash x pro

**Comment by weimo3221** [comment]
这个是只需要下载setup那个文件就可以了吗？

**Comment by ownlight6** [comment]
现在依旧可以
