### ISSUE TITLE
非常感谢第一时间提供汉化包

### ISSUE THREAD

**Issue by panpeach** [ender-zhao/Clash-for-Windows_Chinese#4]
启动弹窗未汉化，配置里编辑规则点不开，其他基本OK……，最好能移除关于界面里的广告（机场引流推广），若移除广告不妥那也无所谓，也不会点进去看的。

**Comment by ender-zhao** [comment]
关于屏蔽广告我会考虑一下的.
编制规则不可用已修复，预计在今天23:00发布.
另外请问 启动弹窗 具体指的是什么？我没找到.

**Comment by ender-zhao** [comment]
编制规则不可用已修复并发布，请重新下载

**Comment by ender-zhao** [comment]
[移除广告的Clash](https://github.com/ender-zhao/Clash-for-Windows_Chinese/releases/tag/Clash-custom-made)

**Comment by panpeach** [comment]
> 关于屏蔽广告我会考虑一下的.
> 编制规则不可用已修复，预计在今天23:00发布.
> 另外请问 启动弹窗 具体指的是什么？我没找到.

![1](https://user-images.githubusercontent.com/13916352/132053299-3d0c28b5-761f-4a6d-b1b1-021e8cd8ec50.jpg)
![2](https://user-images.githubusercontent.com/13916352/132053304-a67804ac-6ff3-4258-b51e-ce416cf6cb30.jpg)
右下角启动时有个弹窗（汉化和未汉化对比）

**Comment by ender-zhao** [comment]
启动弹窗已汉化并发布，请重新下载.
机场专用版的广告已彻底移除，请重新下载.

**Comment by ender-zhao** [comment]
机场专用版的更新已去除，请重新下载.

**Comment by panpeach** [comment]
再次感谢，机场专用版基本完美了。
