### ISSUE TITLE
UWP应用设置出现错误0x57

### ISSUE THREAD

**Issue by xiaomaolu** [ender-zhao/Clash-for-Windows_Chinese#40]
![屏幕截图 2022-06-06 091135](https://user-images.githubusercontent.com/39970457/172079015-594babef-759a-438d-9794-42a1bc4670aa.png)

大佬可以看一下这个问题吗~

**Comment by ender-zhao** [comment]
建议去[Fndroid/clash_for_windows_pkg/issues](https://github.com/Fndroid/clash_for_windows_pkg/issues)提问
