### ISSUE TITLE
hello，接赞助吗😂

### ISSUE THREAD

**Issue by okjiasu** [ender-zhao/Clash-for-Windows_Chinese#41]

**Comment by ender-zhao** [comment]
是什么样的赞助？

**Comment by okjiasu** [comment]
广告费

**Comment by ender-zhao** [comment]
接赞助是可以，但我仅想以超链接到其它页面/库，或以折叠的形式推广，或推广内容不超过两行。如果你不接受这个那就算了。毕竟我并不喜欢广告，我也不认为别人会想看广告

## 例子: 

### [超链接](https://github.com/ender-zhao/Clash-for-Windows_Chinese/issues/41)

<details><summary>折叠:</summary>

  **折叠允许插入链接，图片及标题字体**

  # Example

  [Example](https://github.com/ender-zhao/Clash-for-Windows_Chinese/issues/41)

</details>

**Comment by okjiasu** [comment]
可以，tg联系我@woaiz
