### ISSUE TITLE
或许可以打包成文件夹？

### ISSUE THREAD

**Issue by yzs0324** [ender-zhao/Clash-for-Windows_Chinese#43]
随口一说，feel free to ignore

**Comment by ender-zhao** [comment]
将什么打包为文件夹?

**Comment by yzs0324** [comment]
> 将什么打包为文件夹?

就是Clash.for.Windows-0.19.21-win.7z这个压缩包，解压后就是一堆文件，我的习惯是删掉旧的文件夹然后再建立新的文件夹，所以我觉得打包成文件夹会比较方便。但是现在我意识到你是想让使用者直接覆盖原来文件夹里的文件吧？抱歉提了这么厚脸皮的要求，还请将其无视吧

**Comment by ender-zhao** [comment]
不要点压缩软件提供的解压到当前文件夹就好了（所有的压缩软件应该都有其它的提取选项, 如7-zip的 extract to "XXX\ "），另外，不压缩为文件夹的目的是为了与原版的压缩方式保存一致
