### ISSUE TITLE
您好 一打开tun模式就不能用了

### ISSUE THREAD

**Issue by wanglinzige** [ender-zhao/Clash-for-Windows_Chinese#46]
您好 请问为什么我用系统代理模式就可以用  但是一打开tun模式我就上不了网呢，是软件问题还是因为什么问题呢

**Comment by wanglinzige** [comment]
原版?英文版吗？也会，想着删除重新来但是删除后重新下载那个设置还是在里面
我用v2ray搭配也是不能

**Comment by ender-zhao** [comment]
如果英文版的clash for windows也有问题就去原版那边反馈，没有则是汉化补丁出了问题。（我这边的电脑都是正常使用tun的）

另外，似乎可以通过去tun模式中的设置选项将原dns删除并修改为8.8.8.8或重置Windows的网络设置来解决

**Comment by ender-zhao** [comment]
我遇曾到的问题是规则不生效和clash读取不到链接，这个方法似乎可以解决，但我不确定对你的设备而言一定有效。

或许你可以看看原版Clash for Windows的 [#2497](https://github.com/Fndroid/clash_for_windows_pkg/issues/2497), [#2405](https://github.com/Fndroid/clash_for_windows_pkg/issues/2405) 问题，然后尝试解决

**Comment by wanglinzige** [comment]
还是不行 试咯很久不知道是哪里出了问题 哎，对了老哥 这个运行的时候是不是不需要打开别的翻墙软件

**Comment by ender-zhao** [comment]
可是你为什么要让clash与别的翻墙软件一起使用？

**Comment by wanglinzige** [comment]
我看教程他好像说是需要想有境外环境之后才能去开启 ，如果我现在不打开代理环境直接使用的话（系统代理）是可以的
