### ISSUE TITLE
代理内的选项消失

### ISSUE THREAD

**Issue by phourior** [ender-zhao/Clash-for-Windows_Chinese#49]
![QQ图片20220805221205](https://user-images.githubusercontent.com/63549341/183101597-9f864db5-2de5-4bc6-8522-6ec5d9891a41.png)
如图，之前一直使用正常，打开代理时不小心右下角右键退出后就成这样了

**Comment by ender-zhao** [comment]
未汉化的clash for windows是否有这个问题？
