### ISSUE TITLE
官网网址

### ISSUE THREAD

**Issue by 123qwer123** [ender-zhao/Clash-for-Windows_Chinese#52]
你好
       请问目前最新的官网网是多少,之前收藏的订阅网址,目前打不开了

**Comment by ender-zhao** [comment]
这里与任何机场无任何关联

**Comment by 123qwer123** [comment]
好的,应该是我搞错了&nbsp;&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月30日(星期二) 中午11:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ender-zhao/Clash-for-Windows_Chinese] 官网网址 (Issue #52)





 
这里与任何机场无任何关联
