### ISSUE TITLE
汉化失效

### ISSUE THREAD

**Issue by Spark1ing** [ender-zhao/Clash-for-Windows_Chinese#53]
汉化完成后把图标发送桌面快捷方式，用快捷方式打开就汉化失效吗，必须回到文件夹里去重新打开，这个有办法解决么？

**Comment by ender-zhao** [comment]
快捷方式与是否汉化无关，建议先仔细读说明，然后确认快捷方式的正确性，或者你也可以尝试直接使用完整打包的文件（例如安装程序）
