### ISSUE TITLE
下载需要权限

### ISSUE THREAD

**Issue by Pssss111** [ender-zhao/Clash-for-Windows_Chinese#54]
windowssetup下载不成功

**Comment by ender-zhao** [comment]
具体是怎么不成功？

**Comment by Pssss111** [comment]
我没看懂该怎么操作，你需要我提供更多信息吗，我手机端可以下载朋友传来的base文件成功上网，电脑端不知道下载对应clash




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月8日(星期四) 下午5:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ender-zhao/Clash-for-Windows_Chinese] 下载需要权限 (Issue #54)





 
Closed #54 as completed.
