### ISSUE TITLE
端口提示

### ISSUE THREAD

**Issue by bingjiacai** [ender-zhao/Clash-for-Windows_Chinese#55]
最近更新了之后  发现每次打开都会有 lt seems that Port is not listening, you might need to set a new port. 提示  请问 这个问题是电脑的事还是软件的事   我以前的版本没有出现过这个问题

**Comment by ender-zhao** [comment]
原版的有这个问题吗？

**Comment by bingjiacai** [comment]
原版没有的

**Comment by ender-zhao** [comment]
会影响代理吗？

**Comment by bingjiacai** [comment]
不会

**Comment by ender-zhao** [comment]
那可以给个截图吗

**Comment by bingjiacai** [comment]
![QQ图片20220909164325](https://user-images.githubusercontent.com/54101747/189309976-e1ed3fd9-025e-4dca-8524-e35f88d64ef5.png)

**Comment by ender-zhao** [comment]
切换节点时会出现这个错误提示吗

**Comment by bingjiacai** [comment]
不会

**Comment by bingjiacai** [comment]
就刚打开这个软件的时候会   也不是每次都会  我试了一下  大概平均打开三次会出现两次

**Comment by ender-zhao** [comment]
别的配置文件还会这样吗？

**Comment by bingjiacai** [comment]
这个还没试   我一会儿试试

**Comment by bingjiacai** [comment]
其他配置文件也是有这个问题的

**Comment by bingjiacai** [comment]
汉化后的0.20.0已经没有这个问题了  上个版本不弄也没事了
