### ISSUE TITLE
这个版本配置后面的更新时间没有汉化，之前的都有

### ISSUE THREAD

**Issue by lige47** [ender-zhao/Clash-for-Windows_Chinese#59]
![image](https://user-images.githubusercontent.com/97075835/195976010-7655481c-3b17-4915-952c-432b169331de.png)

**Comment by ender-zhao** [comment]
搞定，请[重新下载一次](https://github.com/ender-zhao/Clash-for-Windows_Chinese/releases/download/CFW-V0.20.5_CN/app.asar)
