### ISSUE TITLE
打开“系统代理”的功能后，“代理组”里的分类名称能汉化吗？

### ISSUE THREAD

**Issue by yexiaoziSAS** [ender-zhao/Clash-for-Windows_Chinese#60]
打开“系统代理”的功能后，“代理组”里的分类名称能汉化吗？如图：
<img width="320" alt="屏幕截图 2022-10-22 162505" src="https://user-images.githubusercontent.com/79674263/197329179-12f68660-437d-4dab-8425-5f451c54f324.png">

**Comment by ender-zhao** [comment]
不能
