### ISSUE TITLE
赞助商OK http 真垃圾，开了一个月都是超时，别挂那了骗子

### ISSUE THREAD

**Issue by Looo3** [ender-zhao/Clash-for-Windows_Chinese#68]

**Comment by Looo3** [comment]
![image](https://user-images.githubusercontent.com/45447411/205641874-05ff4492-0ab9-4ba6-99cb-65422620c283.png)
![image](https://user-images.githubusercontent.com/45447411/205642095-eb39ce03-d8fb-49bd-942f-1e1edf7dc98a.png)

**Comment by ender-zhao** [comment]
# 正如字面意思:
### 赞助商的一切内容与该库无关

![CHACKIT](https://user-images.githubusercontent.com/77391690/205643574-9dfad2ba-d203-44ea-8470-301de6e4034d.png)

这是赞助商的广告，并不是我的推荐。其性质就如同你在网站上看见的Google ads一样。

**而且**，买机场这东西就跟你在理发店充钱一个道理，没准明天就跑路了。
**其次**，没准只有你所在的地方不好用，别的地方的速度又快又稳。
**最后**，嫌弃这个差为什么不直接从一年要花几千的大厂开始尝试呢？或直接搭建个VPS自己维护？又或是向相关部门申请一个合法翻墙专线？

***

另外我在主页写的很清楚：
![CHACK-AGAIN](https://user-images.githubusercontent.com/77391690/205647658-4c64944c-52ce-4bdd-9170-c19f3fb060f6.png)

**下载将代表你对以下内容无任何异议**
**下载将代表你对以下内容无任何异议**
**下载将代表你对以下内容无任何异议**

**Comment by ender-zhao** [comment]
他的科普视频或许对你有帮助
https://www.youtube.com/playlist?list=PLqybz7NWybwUgR-S6m78tfd-lV4sBvGFG

***

不过话说这年头为什么没啥人去读 `安装协议`，`用户协议`， `关于`， `User Agreement` 等字样的内容呢？🤔

**Comment by yaozijin** [comment]
> 

可能是已经习惯被国内某些3A大厂的流氓协议给qj了吧
