### ISSUE TITLE
奇怪的翻译

### ISSUE THREAD

**Issue by ddzzkunye** [ender-zhao/Clash-for-Windows_Chinese#75]
### 你的问题/建议/想说的内容是什么?

![image](https://user-images.githubusercontent.com/92249100/218254161-ee2de16f-f3d6-4e10-8ca0-39ed5513d684.png)
*关闭与链中代理名称的连接*
没看懂

### 版本

CFW0.20.16

**Comment by ender-zhao** [comment]
机翻的问题。意思应该是 `中断所有包含该策略组的连接`，详细来讲，更改规则中的某个组中所使用的节点时将只中断符合那个组中规则的链接，即保留其它不相关的策略组中的连接状态；而全部则会无条件中断所有的连接。

(如果你对于`Close connections with proxy name in chain`你有更好的翻译解释请务必告诉我)

**Comment by ddzzkunye** [comment]
*中断通过该代理节点的链接*吗
