### ISSUE TITLE
你好，这个是只动了app.asar是么？

### ISSUE THREAD

**Issue by cc19264997** [ender-zhao/Clash-for-Windows_Chinese#76]
你好，这个是只动了app.asar么？
剩下其他的文件全都是原版的是么？

其他的文件去除或调整了吗？比如机场引流推荐等

**Comment by ender-zhao** [comment]
是的，仅更改了`app.asar`内的文件。对于此仓库，请阅读README.md中的`下载前你需要知晓的内容:`

**Comment by cc19264997** [comment]
> 是的，仅更改了`app.asar`内的文件。对于此仓库，请阅读README.md中的`下载前你需要知晓的内容:`

感谢付出，ctrl+d了~
