### ISSUE TITLE
一个自该功能出现后(v0.20.5+)一直遗漏的翻译

### ISSUE THREAD

**Issue by szkzn** [ender-zhao/Clash-for-Windows_Chinese#77]
### 遗漏的翻译

从 v0.20.5 开始加了个功能
https://docs.cfw.lbyczf.com/contents/urlscheme.html#%E5%93%8D%E5%BA%94%E5%A4%B4

profile-web-page-url
如果响应头中存在 profile-web-page-url 字段(header)，则在右键点击 profile 菜单中会显示 Open web page 选项，允许用户跳转到对应的门户首页

简单来说，就是机场可以把一个 网址信息附加到了更新订阅的过程，用户在更新订阅时同时会获取机场写入的网址

clash win 客户端读取到该信息，显示该选项，用户右键点击配置文件，第一行就会显示，点击它就能调用浏览器打开订阅时写入的网址

如图所示
![profile-web-page-url](https://p.0z.gs/i/2023/02/17/63eee083ba282.png)

![profile-web-page-url](https://p.0z.gs/i/2023/02/17/63eee5bd0d1a8.png)

这里如果直译，就是 打开网页链接 或保留 URL 不译，打开 网页 URL

但我觉得应该意译好一些，比如 

**打开机场官网** ，个人倾向于这个意思，不知道还有没有更简洁明了的翻译

打开梯子官网
打开机场首页
打开节点提供商的官网

**Comment by ender-zhao** [comment]
会在下个更新添加此汉化 https://github.com/ender-zhao/Clash-for-Windows_Chinese/commit/1605aeb0d235abd0f7c32c9fb85c170b4f36dda6
