### ISSUE TITLE
蓝屏了

### ISSUE THREAD

**Issue by 107295472** [ender-zhao/Clash-for-Windows_Chinese#79]
### 你的问题/建议/想说的内容是什么?

偶尔一次起动后蓝屏了，也没看到蓝屏代码，等一会就重启了

### 版本

0.20.16

**Comment by ender-zhao** [comment]
1. 请先确定是否是由Clash for Windows带来的蓝屏
2. 再使用原版已确定是否是因汉化导致的
3. 如果 是/不是 由汉化版带来的问题，请附上Logs
4. 如果不是由汉化版带来的问题请再带上Log去原版Clash for Windows的Issues反馈
**没有Log神仙也修不了**
