### ISSUE TITLE
任务栏图标消失

### ISSUE THREAD

**Issue by pechpo** [ender-zhao/Clash-for-Windows_Chinese#80]
### 你的问题/建议/想说的内容是什么?

Clash汉化版状态栏图标消失

### 版本

0.20.17

**Comment by ender-zhao** [comment]
状态栏指的是什么？
如果指的是任务栏，那么请检查设置中的`隐藏托盘图标`是否处于关闭状态

**Comment by pechpo** [comment]
![捕获](https://user-images.githubusercontent.com/88359766/223736178-cc14402c-568b-4819-8894-b9b0ce7d2927.PNG)

**Comment by ender-zhao** [comment]
在Windows Sandbox里安装看看是不是正常显示
