### ISSUE TITLE
如何联系制作自定义汉化版？

### ISSUE THREAD

**Issue by Kia678** [ender-zhao/Clash-for-Windows_Chinese#82]
### 催更

看到联系我tg：dhub404

**Comment by Kia678** [comment]
想找你修改制作一下CFW

**Comment by ender-zhao** [comment]
请描述一下具体要修改什么？

**Comment by Kia678** [comment]
移除广告，Clash首页顶部插入一段json直链用来推送显示公告📢，具体请私聊我tg

**Comment by ender-zhao** [comment]
由于最近很忙，仅接受https://github.com/ender-zhao/CFW-custom-made所说明的修改：修改关于中的广告，移除更新，修改部分超链接内容。因此不能在首页插入广告

**Comment by Kia678** [comment]
没问题，那就只做说明中的修改，请联系一下我的tg
