### ISSUE TITLE
覆盖安装完毕显示这个

### ISSUE THREAD

**Issue by lige47** [ender-zhao/Clash-for-Windows_Chinese#86]
### 你的问题/建议/想说的内容是什么?

![捕获](https://user-images.githubusercontent.com/97075835/232182781-d82282c4-8fcb-429a-b5a1-e0c3e1254e4f.PNG)

### 版本

0.20.21

**Comment by ender-zhao** [comment]
卸载重装试试

**Comment by Sohoad** [comment]
我直接覆盖安装没有问题
