### ISSUE TITLE
无法汉化

### ISSUE THREAD

**Issue by zhh1099** [ender-zhao/Clash-for-Windows_Chinese#87]
汉化文件替换后打开应用程序还是英文界面，试过多次，都是一样

**Comment by ender-zhao** [comment]
什么版本？

**Comment by zhh1099** [comment]
已汉化好了，谢谢！

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年4月18日 19:33
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [ender-zhao/Clash-for-Windows_Chinese] 无法汉化 (Issue #87)


什么版本？

―

**Comment by zhh1099** [comment]
好的

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年4月19日 10:46
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [ender-zhao/Clash-for-Windows_Chinese] 无法汉化 (Issue #87)


Closed #87<https://github.com/ender-zhao/Clash-for-Windows_Chinese/issues/87> as completed.

―

**Comment by zhh1099** [comment]
已经汉化成功，非常感谢分享和支持。
