### ISSUE TITLE
关于无法缩小当前使用应用窗口

### ISSUE THREAD

**Issue by lisayyds** [ender-zhao/Clash-for-Windows_Chinese#89]
为什么clashforWindows这个应用点击缩小窗口一直没反应，一直默认最大化

**Comment by Aworld00** [comment]
我目前也遇到了这个问题，甚至退回了几个版本，到19版本才正常；我又安装新版本，发现又可以了，然后今天又遇到了这个问题，上来查看发现这个问题关闭了；然后我翻查了下，发现是我编辑文件的时候按了—F11，再按回去就可以了。。
